#docker-compose.yml
version: '3.4'

services:
  app: 
    image: losimonassi/seller_bot_backend_dev:latest
    container_name: seller_bot_backend_dev
    build: ../../
    depends_on:     
      - database
    ports: 
      - "3000:3000"
    volumes:
      - ../../:/app
    env_file: ../../.env
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/12"

  database:
    container_name: database_seller_bot
    image: postgres:12.1
    volumes:
      - ../../db_data:/var/lib/postgresql/data
      - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  
  sidekiq:
    build: ../../
    volumes:
      - ../../:/app
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
