#docker-compose.yml
version: '3.4'

services:
  app: 
    image: losimonassi/seller_bot_backend:latest
    container_name: seller_bot_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - database
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/12"

  database:
    container_name: database_seller_bot
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data

  sidekiq:
    build: .
    command: sidekiq -r ./path/to/your_project.rb
    volumes:
      - .:/app
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    env_file: .env
    depends_on:
      - redis    
      - database
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
