#docker-compose.yml
version: '3.4'

services:
  app: 
    image: losimonassi/seller_bot_backend:latest
    container_name: seller_bot_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - database
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1

  database:
    container_name: database_seller_bot
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  sidekiq:
    depends_on:
      - database
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/project

volumes:
  gem_cache:
  db_data:
  node_modules:
  redis: