#docker-compose.yml
version: '3.4'

services:
  app: 
    image: losimonassi/seller_bot_backend:latest
    container_name: seller_bot_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: production
      REDIS_URL: "redis://redis:6379/12"

  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data

  sidekiq:
    build: .
    command: sidekiq -r ./path/to/your_project.rb
    volumes:
      - .:/app
    environment:
      RAILS_ENV: "production"
      REDIS_URL: "redis://redis:6379/12"
    env_file: .env
    depends_on:
      - redis 
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  node_modules:
