version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    image: 754630919087.dkr.ecr.us-west-2.amazonaws.com/seller_bot_backend
    container_name: seller_bot_backend
    ports: 
      - "80:3000"
    env_file: .env
    environment:
      RAILS_ENV: production
    restart: always
    # Add any additional production-specific configuration if needed

  # Remove the database service, as we will configure AWS RDS for PostgreSQL separately

  pgadmin:
    container_name: pgadmin4_cgithub.com:w3villa-sujay/seller_bot_backend.gitontainer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

# Remove the volumes section, as we won't need them for production deployment
