#docker-compose.yml
version: '3.4'

services:
  app: 
    image: losimonassi/seller_bot_backend:latest
    depends_on:     
      - database
      - redis
    ports: 
      - "3000:3000"
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    image: losimonassi/seller_bot_backend:latest
    depends_on:
      - app
      - database
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  db_data:

